### ISSUE TITLE
Feature request: Make it easy to to move between opcodes

### ISSUE THREAD

**Issue by zemse** [smlxl/evm.codes#134]
## Motivation

I know there is a search bar on top right, but while I'm viewing some opcode and have to see another one, it needs to be scrolled all the way to the top and click on the search bar. Doing this one or twice might not seem a problem, but imagine writing a bytecode and referring to evm.opcodes and moving through opcodes 100s of times every time need to scroll. I try to get away with hitting Command + F (or Ctrl + F), however, the browser search is terrible it matches so many occurrences that it's more annoying to reach where I want.

## Feature Request

I believe any one of the following can make browsing opcodes fast. (Or if I missed an existing fast way to browse opcodes pls lmk).

- When Command + F is hit, it would be super awesome if the focus moves to the search bar.
- Or if the opcodes are added to kbar, e.g. if I do command + K and type "STATI..." it should show STATICCALL in the dropdown and I can just hit return and it takes the view to the right opcode in the opcodes list.

## Acknowledgements

Really helpful site! If you guys would like, I can make a PR for the above feature, pls lmk what you think.

**Comment by dorlevi** [comment]
Thanks for suggesting this, I agree it could be helpful, I think both suggested implementations are fine, feel free to make a PR and we will review and merge

**Comment by SouravInsights** [comment]
Is anyone working on this issue? @dorlevi @zemse I would love to contribute to this issue.

**Comment by zemse** [comment]
Hey, I haven't been able to prioritise this one yet. Feel free to contribute. Cheers!
