### ISSUE TITLE
Rename Merge to Paris

### ISSUE THREAD

**Issue by axic** [smlxl/evm.codes#192]
It would be nice to display Paris since that is the commonly agreed name.

I think this likely depends on https://github.com/ethereumjs/ethereumjs-monorepo/issues/2360, but perhaps some workaround could be added here.

**Comment by dorlevi** [comment]
Thanks so much for reporting! Yeah, we have a dependency on it and flagged it to the team as we agree with you, having said that, I don't think it makes sense to add some workaround on our end, especially as it'll be even less relevant less fork and we would be left with some hack.

**Comment by axic** [comment]
For anyone looking, while this was closed, it has been implemented since then (through upstream's changes).
