### ISSUE TITLE
Move "About the EVM" tab to the left of "Opcodes"

### ISSUE THREAD

**Issue by devtooligan** [smlxl/evm.codes#207]
<img width="840" alt="Screenshot 2023-02-07 at 7 58 35 AM" src="https://user-images.githubusercontent.com/71567643/217296393-d2cc40c1-6051-46d4-ad22-6bc1d5a40821.png">

After using evm.codes for a couple years I only just discovered the `About the EVM` page.  I think it's a nice resource and a great introduction to the EVM.  But the tab kind of gets hidden being off to the right after Playground and before GitHub.

I propose moving that tab all the way to the left so that it is to the left of Opcodes (and to the right of the evm.codes logo).  This order makes sense to me from a logical perspective, you should know about the basics of the EVM before diving into the opcodes.  Also moving it would give this great resource more exposure allowing more people to benefit from it.

**Comment by dorlevi** [comment]
Sorry for the delay here; I like that you liked the content (especially as I wrote some of it) but I felt that the content we have in the Opcodes/Precompiled and features we have in the playground are a bit more unique, it's something that is not easily available in other resources, so I felt they should be ordered before the "About the EVM" which has information that is a bit more common, does that make sense?
