### ISSUE TITLE
`ISZERO` opcode description

### ISSUE THREAD

**Issue by leovct** [smlxl/evm.codes#250]
Hi, I don't get why the description of the [`ISZERO` opcode](https://www.evm.codes/#15?fork=shanghai) is "Simple not operator". For me, a "simple not operator" typically refers to a unary logical operator that negates a boolean value (e.g. `fn(b: bool) => !b`). Whereas here, the opcode checks if the input value is equal to 0. Maybe something like "Zero Equality Comparison" might be more accurate?

I'd be happy to open a PR if you find it relevant.

**Comment by peroket** [comment]
This is the description from the yellow paper https://ethereum.github.io/yellowpaper/paper.pdf (search for "iszero").
I think this is its description because it is a boolean NOT operator (true becomes false and false becomes true), where "true" is represented by any non zero value.
Does that help?

**Comment by leovct** [comment]
Yes, it makes sense. However, I think the name doesn't exactly describe what it does. I'll keep in mind that this "Simple not operator" really means "Non-zero operator". Thanks for the explanation :)
