### ISSUE TITLE
Mention what happens on insufficient balance during `call()`

### ISSUE THREAD

**Issue by sebastiantf** [smlxl/evm.codes#254]
Mention what happens when an ether transfer occurs from a contract during `call()`, for more amount than the caller's balance. This could arguably be a trivial info to have, but still would be helpful to have a note about this.

Related issue opened on official Solidity docs: https://github.com/ethereum/solidity/issues/14376

**Comment by peroket** [comment]
That's a good point thank you, we will update the doc.
