### ISSUE TITLE
`ecAdd` and `ecMul` revert on invalid input

### ISSUE THREAD

**Issue by pcaversaccio** [smlxl/evm.codes#259]
You state in the precompile section for [`ecAdd`](https://www.evm.codes/precompiled#0x06?fork=shanghai) and [`ecMul`](https://www.evm.codes/precompiled#0x07?fork=shanghai):
> If the input is not valid, or if not enough gas was given, then there is no return data.

![image](https://github.com/smlxl/evm.codes/assets/25297591/1423db8d-9bc4-4314-aea2-3d34969300f9)

This is _not entirely_ correct. In the original [EIP-196](https://eips.ethereum.org/EIPS/eip-196) it's stated that
> Fails on invalid input and consumes all gas provided.

and you see this in the client implementations as well ([example](https://github.com/ethereum/py-evm/blob/c85ef2f2a8cec20299fe164ca3603d26b7c5967d/eth/precompiles/ecadd.py#L43)). So I would suggest reformulating this accordingly with the revert mentioning.

**Comment by peroket** [comment]
Hello, thanks for the comment. I'm not sure if I understand what you are saying, though, because you say we are wrong about the return data, but then you talk about gas.
Can you clarify?

**Comment by peroket** [comment]
Thank you, that makes sense. Feel free to open a PR, otherwise we will do it later :-)

**Comment by pcaversaccio** [comment]
> Thank you, that makes sense. Feel free to open a PR, otherwise we will do it later :-)

See https://github.com/smlxl/evm.codes/pull/261. I quickly checked all precompiles and added the changes where deemed appropriate.

**Comment by peroket** [comment]
Thanks :-)
