### ISSUE TITLE
Opcode 0x44 is not correct in post-merge version

### ISSUE THREAD

**Issue by pldespaigne** [smlxl/evm.codes#263]
This issue is related to #219

The file [`context/ethereumContext.tsx`](https://github.com/smlxl/evm.codes/blob/main/context/ethereumContext.tsx#L456) implement a check to see if the app should display opcode `0x44` as `DIFFICULTY` or `PREVRANDAO` based on the selected fork.

```TypeScript
// TODO: need to implement proper selection of doc according to selected fork (maybe similar to dynamic gas fee)
// Hack for "difficulty" -> "prevrandao" replacement for "merge" HF
if (selectedFork?.name === mergeHardforkName && toHex(op.code) == '44') {
  return {
    ...meta[prevrandaoDocName],
    ...{
      opcodeOrAddress: toHex(op.code),
      staticFee: op.fee,
      minimumFee: 0,
      name: 'PREVRANDAO',
    },
  }
}
```

However this only check for the merge fork, the current live fork is now shangai, so the app will wrongly use `DIFFICULTY` instead of `PREVRANDAO`.

![image](https://github.com/smlxl/evm.codes/assets/5858657/89379794-1eef-403a-803f-2b1b98b3befa)

Anyway thanks a lot for your work!
evm.codes is really awesome and I use it all the time ❤️

**Comment by thevaizman** [comment]
@pldespaigne - thanks for alerting! #264 should fix this issue :)
