### ISSUE TITLE
Feature request: allow bytecode in Playground to start with 0x

### ISSUE THREAD

**Issue by radeksvarz** [smlxl/evm.codes#280]
Bytecode is often represented in hex format with preceding 0x prefix (e.g. `0x6080...`)

Currently the Playground complains:
```
[Error] Only hexadecimal characters are allowed
```
To remove this error one has to delete 0x.

Proposal: 

Allow and ignore 0x prefix for bytecode in Playground.

**Comment by 2xic** [comment]
@radeksvarz thanks for the feedback! You should now be able to have a 0x prefix in the bytecode editor 😄

**Comment by radeksvarz** [comment]
wow, you guys are quick. 👏 Motivates to report more :)
