### ISSUE TITLE
Invalid gas refund on SSTORE

### ISSUE THREAD

**Issue by CodeSandwich** [smlxl/evm.codes#288]
I think that the gas refund calculation may be  invalid. I'm looking at EIP-1283, but AFAIK the refunds were not tweaked in later forks.

---

For `fork=shanghai`, `input = 0, current = 1, original = 1` I'm getting the refund of just 4800:
![image](https://github.com/smlxl/evm.codes/assets/26183680/aa0e78a3-e335-4a13-87f3-ae661dcd83a7)

According to https://eips.ethereum.org/EIPS/eip-1283 the result should be a refund of 15000 because:
> If current value does not equal new value
> If original value equals current value
> If original value is 0 (...) Otherwise, 5000 gas is deducted. If new value is 0, add 15000 gas to refund counter.

---

Another unexpected refund comes for `fork=shanghai`, `input = 1, current = 2, original = 1` I'm getting the refund of just 2800:
![image](https://github.com/smlxl/evm.codes/assets/26183680/a039ecac-4ac5-4184-90bf-478e22b2e775)

According to https://eips.ethereum.org/EIPS/eip-1283 the result should be a refund of 4800 because:
> If current value does not equal new value
> If original value does not equal current value
> If original value equals new value
> If original value is 0 (...) Otherwise, add 4800 gas to refund counter.

I don't think that a refund of 2800 should be even possible.

**Comment by 2xic** [comment]
Hey @CodeSandwich 👋  

Gas refunds have been adjusted a few times and the latest EIP relevant for Shanghai is [EIP-3529](https://eips.ethereum.org/EIPS/eip-3529). 

I compared the expected from EIP-3529 with our calculated output and didn't see anything that was wrong.

**Comment by CodeSandwich** [comment]
Aha, you're right, it's different since London! Thanks for double checking it, and thanks for maintaining evm.codes, it's an invaluable resource :heart:
