### ISSUE TITLE
Redundancy in calldata description

### ISSUE THREAD

**Issue by shandysulen** [smlxl/evm.codes#289]
In [_The calldata_ section of _About the EVM_](https://www.evm.codes/about#calldata), the paragraph begins with:

> The calldata region is the data sent to a transaction as part of a smart contract transaction.

"sent to a transaction as part of a smart contract transaction" caught me off guard when I read it as it seems redundant and just wanted to double-check if it was intentional. Is it meant to be "sent to _an address_ as part of a smart contract transaction"?

**Comment by peroket** [comment]
Thank you for your question :-)

I agree the formulation is not the best here. However, sending to an address has no particular meaning to me. An address is just a (big) number. The data only makes sense in the case of a transaction.

I guess we should just rewrite to "The calldata region is the data sent to a smart contract transaction". What do you think?

**Comment by shandysulen** [comment]
I'm a fan of the rewrite! I find it succint and more clear in its meaning :)
