### ISSUE TITLE
CALLCODE revert behavior described incorrectly

### ISSUE THREAD

**Issue by zobront** [smlxl/evm.codes#298]
In CALLCODE, one of the revert cases is described as:

> The current execution context is from a [STATICCALL](https://www.evm.codes/#FA) and the [value](https://www.evm.codes/#34) (stack index 2) is not 0 (since Byzantium fork).

If we look at [EIP 214](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-214.md#specification) specification, we can see there's a special carve out that CALLCODE with value is acceptable within a STATICCALL.

**Comment by thevaizman** [comment]
@zobront  you're right, thanks for flagging this to us.
Opened #313 to fix this.
