### ISSUE TITLE
UI bug on the main (evm.codes) page

### ISSUE THREAD

**Issue by IaroslavMazur** [smlxl/evm.codes#302]
The minimum gas value is, arguably, too close to the `RETURNDATASIZE` opcode, while completely overlapping with the `RETURNDATACOPY` one:
![image](https://github.com/smlxl/evm.codes/assets/22785348/a84ecfdb-068e-4ff4-8b44-9d03f903eb26)

**Comment by 2xic** [comment]
Did you do anything special to trigger this ? I'm not able to replicate it @IaroslavMazur

**Comment by IaroslavMazur** [comment]
> Did you do anything special to trigger this ? I'm not able to replicate it @IaroslavMazur 

Nothing special.

I'm using Brave on Windows, if that helps.

**Comment by dorlevi** [comment]
I too couldn't reproduce it

**Comment by IaroslavMazur** [comment]
I've got some more context for the isssue described in the OP: I can still reproduce it when I zoom into the [evm.codes](https://www.evm.codes/) page.

More specifically, it happens precisely at the Zoom level of 150%.

@dorlevi, @2xic, could you reopen this issue, please?
