### ISSUE TITLE
Document Ethereum Object Format (EOF) V1

### ISSUE THREAD

**Issue by PaulRBerg** [smlxl/evm.codes#329]
EOF V1 will be introduced in the Pectra hardfork.

Sources:

- https://eips.ethereum.org/EIPS/eip-3540
- https://github.com/ipsilon/eof/blob/main/spec/eof.md
- https://x.com/jtriley_eth/status/1786120858685305178

**Comment by hangleang** [comment]
I was first would like to create an issue for working on documenting EOFv1 for [bounty](https://www.bountycaster.xyz/bounty/0xdad6bb6929454644546f7015cc4373582123452f), then just realized there is an already open issue for it. so, I would like to extend on this with some general plan of implementing:

- [x] switching for show EOF opcodes
![eof-toggle](https://imagedelivery.net/BXluQx4ige9GuW0Ia56BHw/5c855165-46ed-4be0-a39a-00735f1b8800/original)
- [ ] figure out how to add `@ethereumjs/common` with EOF supported from their monorepo, I've been tried to use [GitPkg with custom script](https://gitpkg.vercel.app/about/guide#custom-scripts), but could not build the package
- [ ] add opcodes from [EIP-4200](https://eips.ethereum.org/EIPS/eip-4200) EOF - Static relative jumps: `RJUMP`, `RJUMPI` and `RJUMPV`
- [ ] add opcodes from [EIP-4750](https://eips.ethereum.org/EIPS/eip-4750): EOF - Subroutine: `CALLF` and `RETF`
- [ ] add opcodes from [EIP-6206](https://eips.ethereum.org/EIPS/eip-6206): EOF - Subroutine: `JUMPF`
- [ ] add opcodes from [EIP-7480](https://eips.ethereum.org/EIPS/eip-7480): EOF - Data access: `DATALOAD`, `DATALOADN`, `DATASIZE` and `DATACOPY`
- [ ] add opcodes from [EIP-663](https://eips.ethereum.org/EIPS/eip-663): Stack manipulation: `SWAPN`, `DUPN` and `EXCHANGE`
- [ ] add opcodes from [EIP-7069](https://eips.ethereum.org/EIPS/eip-7069): Revamped CALL instructions: `EXTCALL`, `EXTDELEGATECALL`, `EXTSTATICCALL` and `RETURNDATALOAD`
- [ ] add opcodes from [EIP-7620](https://eips.ethereum.org/EIPS/eip-7620): EOF Creation: `EOFCREATE` and `RETURNCONTRACT`

Thanks to @dorlevi for posting the bounty, and @rakita for this [great reference](https://rakita.github.io/blog/EVM%20(EOF)%20Taxonomy.png)

Additional Resources:
- https://evmobjectformat.org/
- [Mega EOF](https://eips.ethereum.org/EIPS/eip-7692)
- https://rakita.github.io/blog/blog/004-eof-benefits/

**Comment by dorlevi** [comment]
Added
