### ISSUE TITLE
Application Error when using links to some instructions.

### ISSUE THREAD

**Issue by UB18Aux** [smlxl/evm.codes#345]
How to Reproduce:

1. Open https://www.evm.codes/
2. Click on the purple link symbol next to any opcode coming after 9F - SWAP16, for example: F3 - RETURN
3. Copy the URL, for example: https://www.evm.codes/#f3?fork=cancun
4. Open a new tab, open the URL

I get an `Application error: a client-side exception has occurred (see the browser console for more information).`

Console Output:
```Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. [markup.js:250:53](resource://devtools/server/actors/highlighters/utils/markup.js)
Error: Missing parameter value for returnGas
    NextJS 67
[framework-f5033147516daa25.js:1:82745](https://www.evm.codes/_next/static/chunks/framework-f5033147516daa25.js)
Error: Missing parameter value for returnGas
    NextJS 67
[main-278ff518104edf98.js:1:6876](https://www.evm.codes/_next/static/chunks/main-278ff518104edf98.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [main-278ff518104edf98.js:1:6893](https://www.evm.codes/_next/static/chunks/main-278ff518104edf98.js)
Uncaught (in promise) Error: Missing parameter value for ecRecoverGas
    NextJS 49
```

System:
- Firefox 130.0 (64 bit)
- Ubuntu

Just confirmed that the same happens on other devices, like Safari on an iPhone

**Comment by 2xic** [comment]
Fixed now, sorry for the delay, let us know if you still have any issues

**Comment by UB18Aux** [comment]
Works like a charm :) Thank you for fixing it
