### ISSUE TITLE
Bug: Question marks and gas estimation helpers do not show up on first load

### ISSUE THREAD

**Issue by Philogy** [smlxl/evm.codes#350]
When navigating to evm.codes directly the gas estimation helpers are not shown when you go look at an opcode. You have to explicitly select a hardfork (even though Cancun is already selected by default) for it to show up.

Example here of what this looks:
![image](https://github.com/user-attachments/assets/0037f333-a61d-4b65-abd7-73b2b657271e)

Browser: Brave, OS: MacOS

**Comment by 2xic** [comment]
Thanks for the report, was able to reproduce the bug. I'll create a fix within a few days 🫡 

(sorry if there are delays, we are currently spending most of our focus on building [sim.io](https://sim.io/))
